### PR TITLE
Properly handle missing commit signatures

### LINKED ISSUE #704: Commit signatures may be empty/missing
Tendermint rpc can return an empty field here: https://github.com/cosmos/cosmjs/blob/main/packages/tendermint-rpc/src/tendermint34/adaptors/v0-34/responses.ts#L421

I got the following error querying musselnet:

```
(node:66990) UnhandledPromiseRejectionWarning: Error: Value must not be null
    at assertSet (/home/ethan/js/ts-relayer/node_modules/@cosmjs/tendermint-rpc/build/tendermint34/encodings.js:16:15)
    at Object.assertNotEmpty (/home/ethan/js/ts-relayer/node_modules/@cosmjs/tendermint-rpc/build/tendermint34/encodings.js:107:5)
    at decodeCommitSignature (/home/ethan/js/ts-relayer/node_modules/@cosmjs/tendermint-rpc/build/tendermint34/adaptors/v0-34/responses.js:182:54)
    at Array.map (<anonymous>)
    at decodeCommit (/home/ethan/js/ts-relayer/node_modules/@cosmjs/tendermint-rpc/build/tendermint34/adaptors/v0-34/responses.js:190:62)
    at decodeCommitResponse (/home/ethan/js/ts-relayer/node_modules/@cosmjs/tendermint-rpc/build/tendermint34/adaptors/v0-34/responses.js:197:17)
    at decodeCommit (/home/ethan/js/ts-relayer/node_modules/@cosmjs/tendermint-rpc/build/tendermint34/adaptors/v0-34/responses.js:354:16)
    at Tendermint34Client.doCall (/home/ethan/js/ts-relayer/node_modules/@cosmjs/tendermint-rpc/build/tendermint34/tendermint34client.js:263:16)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async IbcClient.getSignedHeader (/home/ethan/js/ts-relayer/build/main/lib/ibcclient.js:170:58)
```

Please make it optional (and maybe investigate a bit more first if you wish, there may be other aspects)

### PR DESCRIPTION
**Pull request by ethanfrey**
Closes #704 

Needed for the relayer to connect to musselnet. 

Can we backport this to a 0.24.1 release? Easier to update the relayer, but I can also just follow 0.25.0-alphas

### CODE REVIEW

**Comment by webmaster128** [comment]
> Can we backport this to a 0.24.1 release?

Can you change the target branch to 0.24? Then you get a backport

File: packages/tendermint-rpc/src/tendermint34/adaptors/v0-34/responses.ts [hunk 1]
```diff
@@ -414,11 +414,13 @@ type RpcSignature = {
...
 function decodeCommitSignature(data: RpcSignature): CommitSignature {
+  const nonZeroTime = data.timestamp && !data.timestamp.startsWith("0001-01-01");
   return {
     blockIdFlag: decodeBlockIdFlag(data.block_id_flag),
     validatorAddress: fromHex(data.validator_address),
-    timestamp: fromRfc3339WithNanoseconds(assertNotEmpty(data.timestamp)),
-    signature: fromBase64(assertNotEmpty(data.signature)),
+    timestamp: nonZeroTime ? fromRfc3339WithNanoseconds(data.timestamp) : undefined,
+    // FIXME: make this optional in type? (signature?: Uint8Array)
+    signature: fromBase64(optional(data.signature, "")),
```
Comment (webmaster128) [inline packages/tendermint-rpc/src/tendermint34/adaptors/v0-34/responses.ts:423]: Could you fix the type in `RpcSignature` above based on your findings to `string | null`?

Comment (ethanfrey) [reply packages/tendermint-rpc/src/tendermint34/adaptors/v0-34/responses.ts:423]: After reviewing the tendermint output carefully, this is always returned as "" for empty, never missing. The current types are correct. The comment can be removed

**Comment by webmaster128** [comment]
I'm taking over this branch now

**Comment by ethanfrey** [comment]
Thank you
