### PR TITLE
Fix Tendermint RPC Commit signature types

### LINKED ISSUE #658: Incorrect type for Commit in tendermint-rpc
Running simapp (from scripts) and querying a commit gives me:

`curl http://localhost:26658/commit | jq .result.signed_header.commit`

```json
{
  "height": "21",
  "round": 0,
  "block_id": {
    "hash": "7E259DA907B95BB56E28B2041D7A19FD1E58ADB0494965C15A8D4719C67EC089",
    "parts": {
      "total": 1,
      "hash": "2F24E85EC71C73B04A5723A743C3171C181E59FE03C523D609A9D43978411ED2"
    }
  },
  "signatures": [
    {
      "block_id_flag": 2,
      "validator_address": "E359FA31E749FFDC571AA4E5F629F70CD53D328A",
      "timestamp": "2021-02-10T12:25:34.578877636Z",
      "signature": "ezhYxn2ktbFf2k2MKQovSyaXrxfx24cxpr8res8/LPZEKcGOHckwnjRuUlM9HKYjNduY3VWU+IiDlHXyzEL2Aw=="
    }
  ]
}
```

The current [Commit response from tendermint-rpc](https://github.com/CosmWasm/cosmjs/blob/52dc82bbe4799c2b4fcd1e69a81c9980ffcdc7c8/packages/tendermint-rpc/src/responses.ts#L223-L227) is quite different: 

```ts
export interface Commit {
  readonly blockId: BlockId;
  readonly signatures: readonly ValidatorSignature[];
}

export type ValidatorSignature = ValidatorEd25519Signature;

export interface ValidatorEd25519Signature {
  readonly algorithm: "ed25519";
  readonly data: Uint8Array;
}
```

Basically, `round` must be added and the `signatures` array looks quite different

You can look at the types from `tendermint/types/types.ts` in the protobuf definitions as a reference to what the rpc endpoint returns: https://github.com/confio/ts-relayer/blob/b0c348c417803fcdc4cac2bfe3b83413bf41a94d/src/codec/tendermint/types/types.ts#L176-L191 (and maybe just copy in those types)

### PR DESCRIPTION
**Pull request by willclarktech**
Closes #658

### CODE REVIEW

File: packages/tendermint-rpc/src/types.ts [hunk 1]
```diff
@@ -22,3 +22,18 @@ export interface ValidatorEd25519Signature {
  * Currently only Ed25519 supported.
  */
 export type ValidatorSignature = ValidatorEd25519Signature;
+
+export enum BlockIdFlag {
+  BlockIdFlagUnknown = 0,
+  BlockIdFlagAbsent = 1,
+  BlockIdFlagCommit = 2,
+  BlockIdFlagNil = 3,
```
Comment (webmaster128) [inline packages/tendermint-rpc/src/types.ts:30]: Do we really want to releat the enum name in the cases? As far as I can tell, we must write them anyways (`BlockIdFlag.BlockIdFlagCommit`)

File: packages/tendermint-rpc/src/types.ts [hunk 2]
```diff
@@ -22,3 +22,18 @@ export interface ValidatorEd25519Signature {
...
+  Unrecognized = -1,
+}
+
+export interface CommitSignature {
+  blockIdFlag: BlockIdFlag;
+  validatorAddress: Uint8Array;
+  timestamp?: Date;
+  signature: ValidatorSignature;
+}
```
Comment (webmaster128) [inline packages/tendermint-rpc/src/types.ts:39]: Do we need the new types in index.ts?

**Review by webmaster128 — COMMENTED** [review]
Is this change compatible to both Tendermint 0.33 and 0.34?

**Comment by ethanfrey** [comment]
> Is this change compatible to both Tendermint 0.33 and 0.34?

I adjusted the proofOp recently, even though it was for 0.34 not 0.33. However, as now one is using proofs with tendermint 0.33, it is breaking an unused functionality.

Either we keep doing that for such features that are different or bite the bullet and make a new 0.34 version.

I must say that there was no failing test nor any user complaints on this functionality before, so it is safe to say it will not break much. However, we could be clear and rename the adaptor to v0.34 and use a v0.33 alias, saying "it is compatible for normal usage, but not for commits or proofs"

File: packages/tendermint-rpc/src/adaptors/v0-33/responses.ts [hunk 3]
```diff
@@ -396,6 +397,18 @@ function decodeBroadcastTxCommit(data: RpcBroadcastTxCommitResponse): responses.
   };
 }
 
+function decodeValidatorSignature(signature: string): ValidatorSignature {
```
Comment (ethanfrey) [inline packages/tendermint-rpc/src/adaptors/v0-33/responses.ts:400]: Since you are just guessing at the algorithm anyway, let's just decode it and return it as Uint8Array.

https://github.com/confio/ts-relayer/blob/b0c348c417803fcdc4cac2bfe3b83413bf41a94d/src/codec/tendermint/types/types.ts#L189 is just a Uint8Array and I will need to convert into that to submit it anyway. The algorithm info is available in the validator pubkey (which is a different endpoint)

File: packages/tendermint-rpc/src/adaptors/v0-33/responses.ts [hunk 4]
```diff
@@ -405,22 +418,28 @@ type RpcSignature = {
...
 };
 
-function decodeSignature(data: RpcSignature): ValidatorSignature {
+function decodeCommitSignature(data: RpcSignature): CommitSignature {
   return {
-    algorithm: "ed25519",
-    data: fromBase64(assertNotEmpty(data.signature)),
+    blockIdFlag: decodeBlockIdFlag(data.block_id_flag),
+    validatorAddress: fromHex(data.validator_address),
+    timestamp: new Date(assertNotEmpty(data.timestamp)),
```
Comment (ethanfrey) [inline packages/tendermint-rpc/src/adaptors/v0-33/responses.ts:425]: Thanks for the Date and not ReadonlyDate here :)

**Comment by webmaster128** [comment]
> Either we keep doing that for such features that are different or bite the bullet and make a new 0.34 version.

I'm fine either way. #642 is planned anyways. It is just a question of timing.

**Review by ethanfrey — COMMENTED** [review]
Looks good.
Can you add a test case? Just a basic sanity check. Query `/commit` endpoint and get the value. Ensure there is one signature (whatever local app we test against) and all fields are set.

File: packages/tendermint-rpc/src/adaptors/v0-33/responses.ts (hunk 4 above)
Comment (webmaster128) [reply packages/tendermint-rpc/src/adaptors/v0-33/responses.ts:425]: Using `Date` discards information. Do we need fractionl digits 4-9? Then we should create a `DateWithNanoseconds`, which works like `ReadonlyDateWithNanoseconds` but is a `Date` with an extra field that can be assigned to a `Date`.

Comment (ethanfrey) [reply packages/tendermint-rpc/src/adaptors/v0-33/responses.ts:425]: We don't need nanoseconds for now. We could create a new type as well.

**Comment by ethanfrey** [comment]
> I'm fine either way. #642 is planned anyways. It is just a question of timing.

Good point here. Let's do the quick and dirty way now (it is blocking) and then do a nice refactor in #642

File: packages/tendermint-rpc/src/adaptors/v0-33/responses.ts (hunk 4 above)
Comment (willclarktech) [reply packages/tendermint-rpc/src/adaptors/v0-33/responses.ts:425]: Let's make a new type when we need it.

File: packages/tendermint-rpc/src/adaptors/v0-33/responses.ts (hunk 3 above)
Comment (willclarktech) [reply packages/tendermint-rpc/src/adaptors/v0-33/responses.ts:400]: Does this apply to the other responses too, eg voting, that were already using this?

Comment (ethanfrey) [reply packages/tendermint-rpc/src/adaptors/v0-33/responses.ts:400]: Voting? Which endpoint is that? consensus?

I would just run a local simapp and check the rpc response. Otherwise, I suggest looking at tendermint/types dir

Comment (willclarktech) [reply packages/tendermint-rpc/src/adaptors/v0-33/responses.ts:400]: `ValidatorSignature` is also used in the `Vote` type, but looks like this is just exported. I'll update to remove the algorithm guess.

File: packages/tendermint-rpc/src/client.spec.ts [hunk 5]
```diff
@@ -12,7 +12,7 @@ import { ExpectedValues, tendermintInstances } from "./config.spec";
 import { buildQuery } from "./requests";
 import * as responses from "./responses";
 import { HttpClient, RpcClient, WebsocketClient } from "./rpcclients";
-import { chainIdMatcher } from "./testutil.spec";
+import { chainIdMatcher, hexMatcher } from "./testutil.spec";
```
Comment (webmaster128) [inline packages/tendermint-rpc/src/client.spec.ts:15]: `hexMatcher` is unused, isn't it?

**Review by webmaster128 — APPROVED** [review]
